import random

# 2023.4.27
GOOGLE_VOICES = {
 'af-ZA': {'FEMALE': ['af-ZA-Standard-A'], 'MALE': []},
 'ar-XA': {'FEMALE': ['ar-XA-Standard-A',
                      'ar-XA-Standard-D',
                      'ar-XA-Wavenet-A',
                      'ar-XA-Wavenet-D'],
           'MALE': ['ar-XA-Standard-B',
                    'ar-XA-Standard-C',
                    'ar-XA-Wavenet-B',
                    'ar-XA-Wavenet-C']},
 'bg-BG': {'FEMALE': ['bg-BG-Standard-A'], 'MALE': []},
 'bn-IN': {'FEMALE': ['bn-IN-Standard-A',
                      'bn-IN-Wavenet-A'],
           'MALE': ['bn-IN-Standard-B',
                    'bn-IN-Wavenet-B']},
 'ca-ES': {'FEMALE': ['ca-ES-Standard-A'], 'MALE': []},
 'cmn-CN': {'FEMALE': ['cmn-CN-Standard-A',
                       'cmn-CN-Standard-D',
                       'cmn-CN-Wavenet-A',
                       'cmn-CN-Wavenet-D'],
            'MALE': ['cmn-CN-Standard-C',
                     'cmn-CN-Standard-B',
                     'cmn-CN-Wavenet-B',
                     'cmn-CN-Wavenet-C']},
 'cmn-TW': {'FEMALE': ['cmn-TW-Standard-A',
                       'cmn-TW-Wavenet-A'],
            'MALE': ['cmn-TW-Standard-B',
                     'cmn-TW-Standard-C',
                     'cmn-TW-Wavenet-B',
                     'cmn-TW-Wavenet-C']},
 'cs-CZ': {'FEMALE': ['cs-CZ-Standard-A',
                      'cs-CZ-Wavenet-A'], 'MALE': []},
 'da-DK': {'FEMALE': ['da-DK-Standard-D',
                      'da-DK-Standard-E',
                      'da-DK-Standard-A',
                      'da-DK-Wavenet-D',
                      'da-DK-Wavenet-E',
                      'da-DK-Wavenet-A'],
           'MALE': ['da-DK-Standard-C',
                    'da-DK-Wavenet-C']},
 'de-DE': {'FEMALE': ['de-DE-Standard-A',
                      'de-DE-Standard-C',
                      'de-DE-Standard-F',
                      'de-DE-Wavenet-F',
                      'de-DE-Wavenet-A',
                      'de-DE-Wavenet-C',
                      'de-DE-Neural2-C',
                      'de-DE-Neural2-F'],
           'MALE': ['de-DE-Standard-B',
                    'de-DE-Standard-D',
                    'de-DE-Standard-E',
                    'de-DE-Wavenet-B',
                    'de-DE-Wavenet-D',
                    'de-DE-Wavenet-E',
                    'de-DE-Neural2-B',
                    'de-DE-Neural2-D']},
 'el-GR': {'FEMALE': ['el-GR-Standard-A',
                      'el-GR-Wavenet-A'], 'MALE': []},
 'en-AU': {'FEMALE': ['en-AU-Standard-A',
                      'en-AU-Standard-C',
                      'en-AU-News-E',
                      'en-AU-News-F',
                      'en-AU-Wavenet-A',
                      'en-AU-Wavenet-C',
                      'en-AU-Neural2-A',
                      'en-AU-Neural2-C'],
           'MALE': ['en-AU-Standard-B',
                    'en-AU-Standard-D',
                    'en-AU-News-G',
                    'en-AU-Wavenet-B',
                    'en-AU-Wavenet-D',
                    'en-AU-Neural2-B',
                    'en-AU-Neural2-D']},
 'en-GB': {'FEMALE': ['en-GB-Standard-A',
                      'en-GB-Standard-C',
                      'en-GB-Standard-F',
                      'en-GB-News-G',
                      'en-GB-News-H',
                      'en-GB-News-I',
                      'en-GB-Wavenet-A',
                      'en-GB-Wavenet-C',
                      'en-GB-Wavenet-F',
                      'en-GB-Neural2-A',
                      'en-GB-Neural2-C',
                      'en-GB-Neural2-F'],
           'MALE': ['en-GB-Standard-B',
                    'en-GB-Standard-D',
                    'en-GB-News-J',
                    'en-GB-News-K',
                    'en-GB-News-L',
                    'en-GB-News-M',
                    'en-GB-Wavenet-B',
                    'en-GB-Wavenet-D',
                    'en-GB-Neural2-B',
                    'en-GB-Neural2-D']},
 'en-IN': {'FEMALE': ['en-IN-Standard-D',
                      'en-IN-Standard-A',
                      'en-IN-Wavenet-D',
                      'en-IN-Wavenet-A'],
           'MALE': ['en-IN-Standard-B',
                    'en-IN-Standard-C',
                    'en-IN-Wavenet-B',
                    'en-IN-Wavenet-C']},
 'en-US': {'FEMALE': ['en-US-Standard-C',
                      'en-US-Standard-E',
                      'en-US-Standard-F',
                      'en-US-Standard-G',
                      'en-US-Standard-H',
                      'en-US-News-K',
                      'en-US-News-L',
                      'en-US-Wavenet-G',
                      'en-US-Wavenet-H',
                      'en-US-Wavenet-C',
                      'en-US-Wavenet-E',
                      'en-US-Wavenet-F',
                      'en-US-Neural2-C',
                      'en-US-Neural2-E',
                      'en-US-Neural2-F',
                      'en-US-Neural2-G',
                      'en-US-Neural2-H',
                      'en-US-Studio-O'],
           'MALE': ['en-US-Standard-A',
                    'en-US-Standard-B',
                    'en-US-Standard-D',
                    'en-US-Standard-I',
                    'en-US-Standard-J',
                    'en-US-News-M',
                    'en-US-News-N',
                    'en-US-Wavenet-I',
                    'en-US-Wavenet-J',
                    'en-US-Wavenet-A',
                    'en-US-Wavenet-B',
                    'en-US-Wavenet-D',
                    'en-US-Neural2-A',
                    'en-US-Neural2-D',
                    'en-US-Neural2-I',
                    'en-US-Neural2-J',
                    'en-US-Studio-M']},
 'es-ES': {'FEMALE': ['es-ES-Standard-A',
                      'es-ES-Standard-C',
                      'es-ES-Standard-D',
                      'es-ES-Wavenet-C',
                      'es-ES-Wavenet-D',
                      'es-ES-Neural2-A',
                      'es-ES-Neural2-C',
                      'es-ES-Neural2-D',
                      'es-ES-Neural2-E'],
           'MALE': ['es-ES-Standard-B',
                    'es-ES-Wavenet-B',
                    'es-ES-Neural2-B',
                    'es-ES-Neural2-F']},
 'es-US': {'FEMALE': ['es-US-Standard-A',
                      'es-US-Wavenet-A',
                      'es-US-News-G',
                      'es-US-News-F',
                      'es-US-Neural2-A'],
           'MALE': ['es-US-Standard-B',
                    'es-US-Standard-C',
                    'es-US-Wavenet-B',
                    'es-US-Wavenet-C',
                    'es-US-News-E',
                    'es-US-News-D',
                    'es-US-Neural2-B',
                    'es-US-Neural2-C',
                    'es-US-Studio-B']},
 'eu-ES': {'FEMALE': ['eu-ES-Standard-A'], 'MALE': []},
 'fi-FI': {'FEMALE': ['fi-FI-Standard-A',
                      'fi-FI-Wavenet-A'], 'MALE': []},
 'fil-PH': {'FEMALE': ['fil-PH-Standard-A',
                       'fil-PH-Standard-B',
                       'fil-PH-Wavenet-A',
                       'fil-PH-Wavenet-B'],
            'MALE': ['fil-PH-Standard-C',
                     'fil-PH-Standard-D',
                     'fil-PH-Wavenet-C',
                     'fil-PH-Wavenet-D']},
 'fr-CA': {'FEMALE': ['fr-CA-Standard-A',
                      'fr-CA-Standard-C',
                      'fr-CA-Wavenet-A',
                      'fr-CA-Wavenet-C',
                      'fr-CA-Neural2-A',
                      'fr-CA-Neural2-C'],
           'MALE': ['fr-CA-Standard-B',
                    'fr-CA-Standard-D',
                    'fr-CA-Wavenet-B',
                    'fr-CA-Wavenet-D',
                    'fr-CA-Neural2-B',
                    'fr-CA-Neural2-D']},
 'fr-FR': {'FEMALE': ['fr-FR-Standard-A',
                      'fr-FR-Standard-C',
                      'fr-FR-Standard-E',
                      'fr-FR-Wavenet-E',
                      'fr-FR-Wavenet-A',
                      'fr-FR-Wavenet-C',
                      'fr-FR-Neural2-A',
                      'fr-FR-Neural2-C',
                      'fr-FR-Neural2-E'],
           'MALE': ['fr-FR-Standard-B',
                    'fr-FR-Standard-D',
                    'fr-FR-Wavenet-B',
                    'fr-FR-Wavenet-D',
                    'fr-FR-Neural2-B',
                    'fr-FR-Neural2-D']},
 'gl-ES': {'FEMALE': ['gl-ES-Standard-A'], 'MALE': []},
 'gu-IN': {'FEMALE': ['gu-IN-Standard-A',
                      'gu-IN-Wavenet-A'],
           'MALE': ['gu-IN-Standard-B',
                    'gu-IN-Wavenet-B']},
 'he-IL': {'FEMALE': ['he-IL-Standard-A',
                      'he-IL-Standard-C',
                      'he-IL-Wavenet-A',
                      'he-IL-Wavenet-C'],
           'MALE': ['he-IL-Standard-D',
                    'he-IL-Standard-B',
                    'he-IL-Wavenet-D',
                    'he-IL-Wavenet-B']},
 'hi-IN': {'FEMALE': ['hi-IN-Standard-D',
                      'hi-IN-Standard-A',
                      'hi-IN-Wavenet-D',
                      'hi-IN-Wavenet-A',
                      'hi-IN-Neural2-A',
                      'hi-IN-Neural2-D'],
           'MALE': ['hi-IN-Standard-B',
                    'hi-IN-Standard-C',
                    'hi-IN-Wavenet-B',
                    'hi-IN-Wavenet-C',
                    'hi-IN-Neural2-B',
                    'hi-IN-Neural2-C']},
 'hu-HU': {'FEMALE': ['hu-HU-Standard-A',
                      'hu-HU-Wavenet-A'], 'MALE': []},
 'id-ID': {'FEMALE': ['id-ID-Standard-A',
                      'id-ID-Standard-D',
                      'id-ID-Wavenet-D',
                      'id-ID-Wavenet-A'],
           'MALE': ['id-ID-Standard-B',
                    'id-ID-Standard-C',
                    'id-ID-Wavenet-B',
                    'id-ID-Wavenet-C']},
 'is-IS': {'FEMALE': ['is-IS-Standard-A'], 'MALE': []},
 'it-IT': {'FEMALE': ['it-IT-Standard-B',
                      'it-IT-Standard-A',
                      'it-IT-Wavenet-A',
                      'it-IT-Wavenet-B',
                      'it-IT-Neural2-A'],
           'MALE': ['it-IT-Standard-C',
                    'it-IT-Standard-D',
                    'it-IT-Wavenet-C',
                    'it-IT-Wavenet-D',
                    'it-IT-Neural2-C']},
 'ja-JP': {'FEMALE': ['ja-JP-Standard-A',
                      'ja-JP-Standard-B',
                      'ja-JP-Wavenet-B',
                      'ja-JP-Wavenet-A',
                      'ja-JP-Neural2-B'],
           'MALE': ['ja-JP-Standard-C',
                    'ja-JP-Standard-D',
                    'ja-JP-Wavenet-C',
                    'ja-JP-Wavenet-D',
                    'ja-JP-Neural2-C',
                    'ja-JP-Neural2-D']},
 'kn-IN': {'FEMALE': ['kn-IN-Standard-A',
                      'kn-IN-Wavenet-A'],
           'MALE': ['kn-IN-Standard-B',
                    'kn-IN-Wavenet-B']},
 'ko-KR': {'FEMALE': ['ko-KR-Standard-A',
                      'ko-KR-Standard-B',
                      'ko-KR-Wavenet-A',
                      'ko-KR-Wavenet-B',
                      'ko-KR-Neural2-A',
                      'ko-KR-Neural2-B'],
           'MALE': ['ko-KR-Standard-C',
                    'ko-KR-Standard-D',
                    'ko-KR-Wavenet-C',
                    'ko-KR-Wavenet-D',
                    'ko-KR-Neural2-C']},
 'lt-LT': {'FEMALE': [], 'MALE': ['lt-LT-Standard-A']},
 'lv-LV': {'FEMALE': [], 'MALE': ['lv-LV-Standard-A']},
 'ml-IN': {'FEMALE': ['ml-IN-Standard-A',
                      'ml-IN-Wavenet-A',
                      'ml-IN-Wavenet-C'],
           'MALE': ['ml-IN-Standard-B',
                    'ml-IN-Wavenet-B',
                    'ml-IN-Wavenet-D']},
 'mr-IN': {'FEMALE': ['mr-IN-Standard-A',
                      'mr-IN-Standard-C',
                      'mr-IN-Wavenet-A',
                      'mr-IN-Wavenet-C'],
           'MALE': ['mr-IN-Standard-B',
                    'mr-IN-Wavenet-B']},
 'ms-MY': {'FEMALE': ['ms-MY-Standard-A',
                      'ms-MY-Standard-C',
                      'ms-MY-Wavenet-A',
                      'ms-MY-Wavenet-C'],
           'MALE': ['ms-MY-Standard-B',
                    'ms-MY-Standard-D',
                    'ms-MY-Wavenet-B',
                    'ms-MY-Wavenet-D']},
 'nb-NO': {'FEMALE': ['nb-NO-Standard-A',
                      'nb-NO-Standard-E',
                      'nb-NO-Standard-C',
                      'nb-NO-Wavenet-A',
                      'nb-NO-Wavenet-C',
                      'nb-NO-Wavenet-E'],
           'MALE': ['nb-NO-Standard-B',
                    'nb-NO-Standard-D',
                    'nb-NO-Wavenet-B',
                    'nb-NO-Wavenet-D']},
 'nl-BE': {'FEMALE': ['nl-BE-Standard-A',
                      'nl-BE-Wavenet-A'],
           'MALE': ['nl-BE-Standard-B',
                    'nl-BE-Wavenet-B']},
 'nl-NL': {'FEMALE': ['nl-NL-Standard-D',
                      'nl-NL-Standard-A',
                      'nl-NL-Standard-E',
                      'nl-NL-Wavenet-D',
                      'nl-NL-Wavenet-A',
                      'nl-NL-Wavenet-E'],
           'MALE': ['nl-NL-Standard-B',
                    'nl-NL-Standard-C',
                    'nl-NL-Wavenet-B',
                    'nl-NL-Wavenet-C']},
 'pa-IN': {'FEMALE': ['pa-IN-Standard-A',
                      'pa-IN-Standard-C',
                      'pa-IN-Wavenet-A',
                      'pa-IN-Wavenet-C'],
           'MALE': ['pa-IN-Standard-B',
                    'pa-IN-Standard-D',
                    'pa-IN-Wavenet-B',
                    'pa-IN-Wavenet-D']},
 'pl-PL': {'FEMALE': ['pl-PL-Standard-A',
                      'pl-PL-Standard-E',
                      'pl-PL-Standard-D',
                      'pl-PL-Wavenet-A',
                      'pl-PL-Wavenet-E',
                      'pl-PL-Wavenet-D'],
           'MALE': ['pl-PL-Standard-B',
                    'pl-PL-Standard-C',
                    'pl-PL-Wavenet-B',
                    'pl-PL-Wavenet-C']},
 'pt-BR': {'FEMALE': ['pt-BR-Standard-A',
                      'pt-BR-Standard-C',
                      'pt-BR-Wavenet-A',
                      'pt-BR-Wavenet-C',
                      'pt-BR-Neural2-A',
                      'pt-BR-Neural2-C'],
           'MALE': ['pt-BR-Standard-B',
                    'pt-BR-Wavenet-B',
                    'pt-BR-Neural2-B']},
 'pt-PT': {'FEMALE': ['pt-PT-Standard-A',
                      'pt-PT-Standard-D',
                      'pt-PT-Wavenet-A',
                      'pt-PT-Wavenet-D'],
           'MALE': ['pt-PT-Standard-B',
                    'pt-PT-Standard-C',
                    'pt-PT-Wavenet-B',
                    'pt-PT-Wavenet-C']},
 'ro-RO': {'FEMALE': ['ro-RO-Standard-A',
                      'ro-RO-Wavenet-A'], 'MALE': []},
 'ru-RU': {'FEMALE': ['ru-RU-Standard-E',
                      'ru-RU-Standard-A',
                      'ru-RU-Standard-C',
                      'ru-RU-Wavenet-E',
                      'ru-RU-Wavenet-A',
                      'ru-RU-Wavenet-C'],
           'MALE': ['ru-RU-Standard-B',
                    'ru-RU-Standard-D',
                    'ru-RU-Wavenet-B',
                    'ru-RU-Wavenet-D']},
 'sk-SK': {'FEMALE': ['sk-SK-Standard-A',
                      'sk-SK-Wavenet-A'], 'MALE': []},
 'sr-RS': {'FEMALE': ['sr-RS-Standard-A'], 'MALE': []},
 'sv-SE': {'FEMALE': ['sv-SE-Standard-B',
                      'sv-SE-Standard-C',
                      'sv-SE-Standard-A',
                      'sv-SE-Wavenet-B',
                      'sv-SE-Wavenet-D',
                      'sv-SE-Wavenet-A'],
           'MALE': ['sv-SE-Standard-D',
                    'sv-SE-Standard-E',
                    'sv-SE-Wavenet-C',
                    'sv-SE-Wavenet-E']},
 'ta-IN': {'FEMALE': ['ta-IN-Standard-C',
                      'ta-IN-Standard-A',
                      'ta-IN-Wavenet-A',
                      'ta-IN-Wavenet-C'],
           'MALE': ['ta-IN-Standard-D',
                    'ta-IN-Standard-B',
                    'ta-IN-Wavenet-B',
                    'ta-IN-Wavenet-D']},
 'te-IN': {'FEMALE': ['te-IN-Standard-A'],
           'MALE': ['te-IN-Standard-B']},
 'th-TH': {'FEMALE': ['th-TH-Standard-A',
                      'th-TH-Neural2-C'], 'MALE': []},
 'tr-TR': {'FEMALE': ['tr-TR-Standard-C',
                      'tr-TR-Standard-D',
                      'tr-TR-Standard-A',
                      'tr-TR-Wavenet-C',
                      'tr-TR-Wavenet-D',
                      'tr-TR-Wavenet-A'],
           'MALE': ['tr-TR-Standard-B',
                    'tr-TR-Standard-E',
                    'tr-TR-Wavenet-B',
                    'tr-TR-Wavenet-E']},
 'uk-UA': {'FEMALE': ['uk-UA-Standard-A',
                      'uk-UA-Wavenet-A'], 'MALE': []},
 'vi-VN': {'FEMALE': ['vi-VN-Standard-A',
                      'vi-VN-Standard-C',
                      'vi-VN-Wavenet-A',
                      'vi-VN-Wavenet-C'],
           'MALE': ['vi-VN-Standard-B',
                    'vi-VN-Standard-D',
                    'vi-VN-Wavenet-B',
                    'vi-VN-Wavenet-D']},
 'yue-HK': {'FEMALE': ['yue-HK-Standard-A',
                       'yue-HK-Standard-C'],
            'MALE': ['yue-HK-Standard-B',
                     'yue-HK-Standard-D']}}


def switch_gender(gender):
    if gender.lower() == 'male':
        return 'FEMALE'
    else:
        return 'MALE'


def select_voice(language_code, gender, kind='Wavenet'):
    gender = gender.upper()
    all_kind_names = GOOGLE_VOICES[language_code][gender]
    if len(all_kind_names) == 0:
        all_kind_names = GOOGLE_VOICES[language_code][switch_gender(gender)]

    names = [name for name in all_kind_names if kind in name]
    if len(names) == 0:
        names = all_kind_names

    return random.choice(names)


if __name__ == '__main__':
    language_code = 'ko-KR'
    gender='female'
    print(select_voice(language_code,gender))
